- name: Installing package
  hosts: all
  become: yes
  tasks:
  - name: installing package
    apt:
      pkg:
      - git
      - postgresql
      - postgresql-contrib
      - libpq-dev
      update_cache: yes

- name: Host1 deployment
  hosts: host1
  become: yes
  tasks:
  - name: installing package
    apt:
      pkg:
      - python3
      - python3-pip

  - name: git clone repositories
    git:
      repo: "{{ hostvars[inventory_hostname]['GIT'] }}"
      dest: "{{ hostvars[inventory_hostname]['WORKDIR'] }}"

  - name: install requirements
    pip:
      requirements: "{{ hostvars[inventory_hostname]['WORKDIR'] }}/bot/requirements.txt"

  - name: sending init.sql to the host1
    copy:
      src: init.sql
      dest: /tmp/init.sql

  - name: changing the owner of init.sql
    command: chown postgres:postgres /tmp/init.sql

  - name: replacing DB_DATABASE with the database name
    replace:
      path: /tmp/init.sql
      regexp: "DB_DATABASE"
      replace: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"

  - name: replacing DB_USER with the database user
    replace:
      path: /tmp/init.sql
      regexp: "DB_USER"
      replace: "{{ hostvars[inventory_hostname]['DB_USER'] }}"

  - name: replacing DB_PASSWORD with the database password
    replace:
      path: /tmp/init.sql
      regexp: "DB_PASSWORD"
      replace: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"

  - name: replacing DB_REPL_USER with the replication database user
    replace:
      path: /tmp/init.sql
      regexp: "DB_REPL_USER"
      replace: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"

  - name: replacing DB_REPL_PASSWORD with the replication database password
    replace:
      path: /tmp/init.sql
      regexp: "DB_REPL_PASSWORD"
      replace: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"

  - name: starting init.sql
    command: /usr/bin/psql -a -f /tmp/init.sql
    become: true
    become_user: postgres

  - name: change postgresql.conf
    blockinfile:
      path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/postgresql.conf"
      block: |
        listen_addresses = '*'
        port = {{ hostvars[inventory_hostname]['DB_PORT'] }}
        max_wal_senders=10
        wal_level=replica
        hot_standby=on
        max_replication_slots=10
        hot_standby_feedback=on
        log_replication_commands=on

  - name: change pg_hba.conf
    blockinfile:
      path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/pg_hba.conf"
      block: |
        local all postgres peer
        host replication all {{ hostvars[inventory_hostname]['ansible_host'] }}/24 scram-sha-256
        host all all {{ hostvars[inventory_hostname]['ansible_host'] }}/32 trust

  - name: restarting postgresql with the main database
    service:
      name: postgresql
      state: restarted

- name: Host2 deployment
  hosts: host2
  become: true
  tasks:
  - name: change postgresql.conf
    become: true
    become_user: postgres
    blockinfile:
      path: "/etc/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/postgresql.conf"
      block: |
        listen_addresses = '*'
        port = {{ hostvars[inventory_hostname]['DB_REPL_PORT'] }}

  - name: remove old database data
    command: rm -rf /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/

  - name: backup from host1
    command: pg_basebackup -R -h {{ hostvars[inventory_hostname]['DB_HOST'] }} -D /var/lib/postgresql/{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}/main/ -p {{ hostvars[inventory_hostname]['DB_PORT'] }} -U {{ hostvars[inventory_hostname]['DB_REPL_USER'] }}
    environment:
      PGUSER: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
      PGPASSWORD: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"

  - name: changing the owner of a directory
    command: chown -R postgres:postgres /var/lib/postgresql/

  - name: restarting postgresql with a replicated database
    service:
      name: postgresql
      state: restarted

- name: project startup
  hosts: host1
  become: yes
  tasks:
  - name: tg_bot startup
    command: python3 "{{ hostvars[inventory_hostname]['WORKDIR'] }}/bot/tg_bot.py"
    environment:
      TOKEN: "{{ hostvars[inventory_hostname]['TOKEN'] }}"
      RM_HOST: "{{ hostvars[inventory_hostname]['RM_HOST'] }}"
      RM_PORT: "{{ hostvars[inventory_hostname]['RM_PORT'] }}"
      RM_USERNAME: "{{ hostvars[inventory_hostname]['RM_USERNAME'] }}"
      RM_PASSWORD: "{{ hostvars[inventory_hostname]['RM_PASSWORD'] }}"
      DB_DATABASE: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
      DB_USER: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
      DB_PASSWORD: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"
      DB_HOST: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
      DB_PORT: "{{ hostvars[inventory_hostname]['DB_PORT'] }}"
      DB_REPL_USER: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
      DB_REPL_PASSWORD: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
      DB_REPL_HOST: "{{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}"
      DB_REPL_PORT: "{{ hostvars[inventory_hostname]['DB_REPL_PORT'] }}"
      POSTGRES_VERSION: "{{ hostvars[inventory_hostname]['POSTGRES_VERSION'] }}"